import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./components/AuthProvider";
const inter = Inter({ subsets: ["latin"] });
import Hydrate from "./components/Hydrate";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import Nav from "./components/Nav";
import { Roboto, Lobster_Two } from "next/font/google";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["400", "500", "700", "900", "300", "100"],
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const sessionServer = await getServerSession(authOptions);
  console.log(sessionServer);
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`${roboto.className}`}>
          <Hydrate>
            <div className="container">
              <Nav
                user={sessionServer?.user}
                expires={sessionServer?.expires as string}
              />
              {children}
              <Footer />
            </div>
          </Hydrate>
        </body>
      </AuthProvider>
    </html>
  );
}
