import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./components/AuthProvider";
const inter = Inter({ subsets: ["latin"] });
import Hydrate from "./components/Hydrate";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import Nav from "./components/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <Nav user={session?.user} expires={session?.expires as string} />
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
